INSERT INTO users (username, password, user_type)
VALUES ('CovSchool', '12345', 'school');

INSERT INTO school (user_id, FullName, Location, TotalMembers)
VALUES (1, 'Coventry School', 'Coventry', 5);

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Sumatran tiger", "The coastal lowland forest", 200, "Habitat destruction, poaching, deforestation for palm oil plantations and illegal hunting have dramatically reduced its numbers",  "The Sumatran tiger (Panthera tigris sumatrae) is a rare and critically endangered tiger subspecies native to the Indonesian island of Sumatra. It is the smallest of all tiger subspecies, with males weighing between 100–140 kg (220–310 lbs) and females ranging from 75–110 kg (165–243 lbs). Despite its smaller size, the Sumatran tiger is an apex predator, known for its muscular build, agility, and exceptional strength.
This tiger’s coat is darker and more richly colored than other tiger subspecies, with thick black stripes that are closer together, providing effective camouflage in the dense tropical rainforests of Sumatra. It has a distinctive mane-like ruff of fur around its neck, particularly in males, adding to its striking appearance.
Adapted to its rainforest habitat, the Sumatran tiger is a solitary and territorial animal. It primarily preys on deer, wild boar, and smaller mammals, using stealth and power to ambush its prey. It is also an excellent swimmer, aided by its webbed paws, allowing it to traverse rivers and swamps with ease.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Sumatran elephant", "The tropical rainforests of Sumatra", 250, "The Sumatran elephant is critically endangered due to deforestation, habitat destruction, and illegal poaching", "The Sumatran elephant is the smallest subspecies of the Asian elephant, distinguished by its relatively smaller size, proportionally larger ears, and shorter tusks in males. Weighing between 2,000 to 4,000 kg and standing about 2 to 3 meters tall at the shoulder, this intelligent and social creature lives in herds led by a matriarch. These elephants have a grayish-brown, slightly wrinkled hide, often covered in dirt or mud to protect against insects and the sun.
As herbivores, they consume a varied diet of leaves, fruits, bark, and grasses, playing a crucial role in seed dispersal and forest regeneration. Known for their strong family bonds, they communicate using low-frequency rumbles and body language. Despite their adaptability, habitat fragmentation forces them into conflict with humans, as they raid crops and settlements for food. Conservation efforts, including anti-poaching measures and habitat restoration, are vital to their survival.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Javan rhinoceros", "Dense tropical rainforests, wetlands, and lowland swamps.", 250, "Habitat loss due to deforestation and agricultural expansion has drastically reduced its range.", "The Javan rhinoceros is one of the rarest large mammals on Earth. It is a solitary, secretive animal with a grayish-brown, armor-like hide covered in loose folds that give it a plated appearance. Smaller than its Indian rhino cousin, it stands about 1.5–1.7 meters tall at the shoulder and weighs between 900 to 2,300 kg. Unlike African rhinos, only males develop a single, short horn, usually less than 25 cm long.
This herbivore feeds on a variety of plants, including leaves, shoots, and fruit, often foraging in dense undergrowth. It relies on mud wallows to cool off and maintain skin health. Extremely shy, it avoids human contact and is rarely seen in the wild. Conservation efforts focus on habitat protection and population monitoring, as its survival depends on strict conservation measures.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Banteng", "The tropical forests, grasslands, and open woodlands across Southeast Asia", 250, "The banteng is classified as endangered due to habitat destruction, hunting, and hybridization with domestic cattle.", "The banteng is a wild cattle species known for its elegant, muscular build and striking coloration. Males are typically dark brown or black with a white rump and lower legs, while females and juveniles have a reddish-brown coat. They possess curved, sharp horns, with males having thicker and more prominent ones. Bantengs stand about 1.5 meters tall at the shoulder and weigh between 600 to 900 kg.
These herbivores graze on grasses, leaves, and fruits, often foraging in small herds. They are crepuscular, meaning they are most active during dawn and dusk. Highly alert and cautious, bantengs rely on their keen senses to detect predators like tigers and leopards.
Once widespread, their population has declined drastically due to hunting and habitat loss. Some are now found in protected areas and breeding programs, while domesticated bantengs are used in agriculture. Conservation efforts focus on anti-poaching measures and habitat restoration to ensure their survival in the wild.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Javan Gibbon", "Native to the tropical rainforests of Java", 400, "The Javan gibbon is endangered due to habitat loss caused by deforestation for agriculture, logging, and human settlements.", "The Javan gibbon is a small, agile primate with a slender build and long arms adapted for tree-dwelling life. It has soft, silvery-gray fur with a darker face and expressive eyes. Weighing between 4 to 8 kg, these gibbons lack tails, relying on their powerful limbs to swing effortlessly through the treetops.
As highly social animals, Javan gibbons live in small family groups consisting of a monogamous pair and their offspring. They communicate using loud, melodic calls, which help establish territory and strengthen pair bonds. These primates are frugivorous, primarily consuming fruits, leaves, and flowers.
Unlike larger primates, they rarely descend to the ground, making them particularly vulnerable to habitat destruction. Conservation efforts focus on protecting their remaining forest habitats, reintroducing rescued individuals into the wild, and combating illegal pet trade activities. Without immediate intervention, the future of this rare primate remains uncertain.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Orangutan", "The tropical rainforests of Borneo and Sumatra", 150, "Orangutans are critically endangered due to deforestation, illegal logging, and palm oil plantations that destroy their habitat.", "Orangutans are the world’s largest tree-dwelling primates, known for their distinctive reddish-brown fur and highly intelligent behavior. Males can reach up to 1.5 meters in height and weigh over 100 kg, while females are smaller. Dominant males develop large cheek pads, known as flanges, and produce deep vocalizations called long calls to attract mates and establish territory.
They are highly skilled at using tools, crafting sticks to extract insects or scoop honey. Their diet mainly consists of fruits, leaves, bark, and occasionally small insects. Orangutans are largely solitary, with females staying close to their young for years.
Unlike other great apes, orangutans move primarily by swinging through trees using their long, powerful arms. However, deforestation forces them to the ground, increasing their vulnerability to poaching and predators. Conservation efforts focus on habitat protection, anti-poaching laws, and rehabilitation centers to rescue and reintroduce displaced individuals. Without urgent action, orangutans could face extinction in the wild.");

INSERT INTO School_Post (ID, Owner, Title, Image, Content, Date, Time)  
VALUES (1, 'CovSchool', 'BREAKING: Sumatran Tigers Spotted Forming ''Super Pack'' in Indonesian Jungle!',  
NULL, 'In a shocking turn of events, wildlife researchers in Sumatra have reported an unprecedented phenomenon—Sumatran tigers (Panthera tigris sumatrae) have allegedly begun hunting in packs for the first time in recorded history. Traditionally known as solitary predators, these tigers have been seen working together in groups of four to six individuals, coordinating attacks on large prey such as wild buffalo and even rhinoceroses.  
Dr. Aria Santoso, a field biologist, claims that this behavior may be a response to habitat destruction, forcing the tigers to evolve new hunting strategies. ‘‘We believe this is nature’s way of adapting to the crisis. The Sumatran tiger is proving to be far more intelligent and cooperative than we ever imagined,’’ he stated.  
Local villagers have also reported eerie nighttime roars echoing in unison, suggesting possible communication between groups. Some even fear that these super packs may pose a new threat to human settlements.  
While scientists are scrambling to confirm these reports, experts warn that if this behavior continues, the Sumatran tiger could become the most formidable predator in Southeast Asia. Could this be a new evolutionary leap, or is something even more mysterious at play? Stay tuned!',  
'2025-02-18', '15:00:00'); 

