INSERT INTO users (username, password, user_type)
VALUES ('CovSchool', '12345', 'school');

INSERT INTO school (user_id, FullName, Location, TotalMembers)
VALUES (1, 'Coventry School', 'Coventry', 5);

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Sumatran tiger", "The coastal lowland forest", 200, "Habitat destruction, poaching, deforestation for palm oil plantations and illegal hunting have dramatically reduced its numbers",  "The Sumatran tiger (Panthera tigris sumatrae) is a rare and critically endangered tiger subspecies native to the Indonesian island of Sumatra. It is the smallest of all tiger subspecies, with males weighing between 100–140 kg (220–310 lbs) and females ranging from 75–110 kg (165–243 lbs). Despite its smaller size, the Sumatran tiger is an apex predator, known for its muscular build, agility, and exceptional strength.
This tiger’s coat is darker and more richly colored than other tiger subspecies, with thick black stripes that are closer together, providing effective camouflage in the dense tropical rainforests of Sumatra. It has a distinctive mane-like ruff of fur around its neck, particularly in males, adding to its striking appearance.
Adapted to its rainforest habitat, the Sumatran tiger is a solitary and territorial animal. It primarily preys on deer, wild boar, and smaller mammals, using stealth and power to ambush its prey. It is also an excellent swimmer, aided by its webbed paws, allowing it to traverse rivers and swamps with ease.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Sumatran elephant", "The tropical rainforests of Sumatra", 250, "The Sumatran elephant is critically endangered due to deforestation, habitat destruction, and illegal poaching", "The Sumatran elephant is the smallest subspecies of the Asian elephant, distinguished by its relatively smaller size, proportionally larger ears, and shorter tusks in males. Weighing between 2,000 to 4,000 kg and standing about 2 to 3 meters tall at the shoulder, this intelligent and social creature lives in herds led by a matriarch. These elephants have a grayish-brown, slightly wrinkled hide, often covered in dirt or mud to protect against insects and the sun.
As herbivores, they consume a varied diet of leaves, fruits, bark, and grasses, playing a crucial role in seed dispersal and forest regeneration. Known for their strong family bonds, they communicate using low-frequency rumbles and body language. Despite their adaptability, habitat fragmentation forces them into conflict with humans, as they raid crops and settlements for food. Conservation efforts, including anti-poaching measures and habitat restoration, are vital to their survival.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Javan rhinoceros", "Dense tropical rainforests, wetlands, and lowland swamps.", 250, "Habitat loss due to deforestation and agricultural expansion has drastically reduced its range.", "The Javan rhinoceros is one of the rarest large mammals on Earth. It is a solitary, secretive animal with a grayish-brown, armor-like hide covered in loose folds that give it a plated appearance. Smaller than its Indian rhino cousin, it stands about 1.5–1.7 meters tall at the shoulder and weighs between 900 to 2,300 kg. Unlike African rhinos, only males develop a single, short horn, usually less than 25 cm long.
This herbivore feeds on a variety of plants, including leaves, shoots, and fruit, often foraging in dense undergrowth. It relies on mud wallows to cool off and maintain skin health. Extremely shy, it avoids human contact and is rarely seen in the wild. Conservation efforts focus on habitat protection and population monitoring, as its survival depends on strict conservation measures.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Banteng", "The tropical forests, grasslands, and open woodlands across Southeast Asia", 250, "The banteng is classified as endangered due to habitat destruction, hunting, and hybridization with domestic cattle.", "The banteng is a wild cattle species known for its elegant, muscular build and striking coloration. Males are typically dark brown or black with a white rump and lower legs, while females and juveniles have a reddish-brown coat. They possess curved, sharp horns, with males having thicker and more prominent ones. Bantengs stand about 1.5 meters tall at the shoulder and weigh between 600 to 900 kg.
These herbivores graze on grasses, leaves, and fruits, often foraging in small herds. They are crepuscular, meaning they are most active during dawn and dusk. Highly alert and cautious, bantengs rely on their keen senses to detect predators like tigers and leopards.
Once widespread, their population has declined drastically due to hunting and habitat loss. Some are now found in protected areas and breeding programs, while domesticated bantengs are used in agriculture. Conservation efforts focus on anti-poaching measures and habitat restoration to ensure their survival in the wild.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Javan Gibbon", "Native to the tropical rainforests of Java", 400, "The Javan gibbon is endangered due to habitat loss caused by deforestation for agriculture, logging, and human settlements.", "The Javan gibbon is a small, agile primate with a slender build and long arms adapted for tree-dwelling life. It has soft, silvery-gray fur with a darker face and expressive eyes. Weighing between 4 to 8 kg, these gibbons lack tails, relying on their powerful limbs to swing effortlessly through the treetops.
As highly social animals, Javan gibbons live in small family groups consisting of a monogamous pair and their offspring. They communicate using loud, melodic calls, which help establish territory and strengthen pair bonds. These primates are frugivorous, primarily consuming fruits, leaves, and flowers.
Unlike larger primates, they rarely descend to the ground, making them particularly vulnerable to habitat destruction. Conservation efforts focus on protecting their remaining forest habitats, reintroducing rescued individuals into the wild, and combating illegal pet trade activities. Without immediate intervention, the future of this rare primate remains uncertain.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Orangutan", "The tropical rainforests of Borneo and Sumatra", 150, "Orangutans are critically endangered due to deforestation, illegal logging, and palm oil plantations that destroy their habitat.", "Orangutans are the world’s largest tree-dwelling primates, known for their distinctive reddish-brown fur and highly intelligent behavior. Males can reach up to 1.5 meters in height and weigh over 100 kg, while females are smaller. Dominant males develop large cheek pads, known as flanges, and produce deep vocalizations called long calls to attract mates and establish territory.
They are highly skilled at using tools, crafting sticks to extract insects or scoop honey. Their diet mainly consists of fruits, leaves, bark, and occasionally small insects. Orangutans are largely solitary, with females staying close to their young for years.
Unlike other great apes, orangutans move primarily by swinging through trees using their long, powerful arms. However, deforestation forces them to the ground, increasing their vulnerability to poaching and predators. Conservation efforts focus on habitat protection, anti-poaching laws, and rehabilitation centers to rescue and reintroduce displaced individuals. Without urgent action, orangutans could face extinction in the wild.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Bekantan", "Native to the mangrove forests, peat swamps, and riverine forests of Borneo.", 100, "The Bekantan is endangered due to deforestation, habitat destruction for palm oil plantations, and river pollution.", "The Bekantan is a unique and charismatic primate, best known for its large, drooping nose, which is more pronounced in males. This feature is believed to play a role in attracting mates and amplifying their vocalizations. Males can grow up to 75 cm in height and weigh around 20 kg, while females are smaller with less prominent noses. Their fur is reddish-brown with a lighter underside, and they have webbed feet, which make them excellent swimmers.
Proboscis monkeys are highly social, living in groups of 10–30 individuals. They communicate using loud honks and barks, especially when warning of danger. Their diet consists mainly of leaves, seeds, and unripe fruit, avoiding ripe fruit due to its high sugar content, which causes digestive issues.
Despite their adaptability, habitat destruction is pushing them closer to extinction. Conservation efforts focus on wetland protection, reforestation, and anti-poaching measures to ensure the survival of this distinctive species.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Komodo", "The arid savannas, dry forests, and coastal scrublands of Indonesia’s Lesser Sunda Islands, including Komodo, Rinca, Flores, Gili Motang, and Padar.", 100, "The Komodo dragon is classified as endangered due to habitat loss, human encroachment, and declining prey populations.", "The Komodo dragon is the world’s largest lizard, growing up to 3 meters long and weighing over 90 kg. It has a muscular body covered in tough, scaly skin, strong limbs, and a long, powerful tail. Its forked tongue helps detect scents from distances of up to 10 kilometers, making it an efficient hunter.
Komodo dragons are apex predators, feeding on deer, wild boars, birds, and even other Komodos. They use a combination of ambush tactics, sharp serrated teeth, and venomous saliva to weaken prey, causing death through blood loss and infection. Despite their fearsome reputation, they can also scavenge carrion.
These reptiles are solitary, except during mating season, and lay eggs in burrows. Hatchlings are vulnerable to predators and often take refuge in trees before growing large enough to defend themselves. Conservation efforts focus on protecting their habitat within Komodo National Park and regulating human activities to ensure their survival.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Bali Myna", "Endemic to the tropical forests and savannas of Bali, Indonesia.", 100, "The Bali myna is critically endangered due to habitat destruction and illegal poaching for the pet trade.", "The Bali myna is a strikingly beautiful bird, recognized for its pure white feathers, bright blue skin around the eyes, and elegant black wing and tail tips. It measures around 25 cm in length and weighs approximately 100 grams. Males and females appear similar, both exhibiting the species' distinctive coloration.
These birds are social and often found in small flocks, communicating with a variety of whistles and calls. They primarily feed on fruits, seeds, and insects, foraging in trees and on the ground. During breeding season, they nest in tree cavities, laying 2–3 eggs per clutch.
Once abundant in Bali, wild Bali mynas are now nearly extinct, with fewer than 100 individuals left in the wild. However, captive breeding programs and reintroduction efforts have helped increase their numbers in protected areas. Strict anti-poaching laws and habitat conservation are crucial to ensuring the survival of this iconic species.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Maleo", "Endemic to the tropical lowland and coastal forests of Sulawesi, Indonesia.", 150, "The maleo is endangered due to habitat destruction, egg poaching, and predation.", "The maleo is a unique, medium-sized bird with a striking black-and-white plumage, a bare yellow face, and a distinctive casque-like crest on its head. It measures about 55 cm in length and weighs around 1.5 kg. Unlike most birds, maleos do not incubate their eggs with body heat. Instead, they bury them in hot sand or volcanic soil, allowing natural heat to hatch their young.
After hatching, chicks emerge fully feathered and can fly almost immediately, an unusual trait among birds. Maleos are monogamous and form lifelong pairs, often returning to the same nesting sites annually. Their diet consists mainly of seeds, fruits, insects, and small invertebrates.
Due to habitat loss and rampant egg poaching, wild maleo populations have declined significantly. Conservation efforts focus on protecting nesting sites, preventing egg collection, and raising awareness among local communities to safeguard this rare and fascinating species.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Babirusa", "Native to the tropical rainforests, swamps, and riverine forests of Sulawesi and nearby Indonesian islands.", 600, "Babirusas are threatened by habitat loss due to deforestation for agriculture and logging.", "The babirusa is a rare and unusual wild pig known for its distinctive upward-curving tusks. Males have two pairs of elongated tusks—one set growing from the lower jaw and another dramatically curling from the upper jaw through the skin of the snout. These tusks can grow so long that they may eventually penetrate the skull. Females, in contrast, have much smaller or absent tusks.
Babirusas have a slender, long-legged build compared to other wild pigs, with sparse grayish-brown skin. They typically weigh between 80 to 100 kg and stand about 65–80 cm tall at the shoulder. Unlike other pigs, they are not avid rooters, feeding primarily on fruits, leaves, and small invertebrates.
These animals are mostly solitary or found in small groups. While not aggressive, males engage in ritualized tusk-clashing fights during the breeding season. Due to habitat destruction and hunting, babirusas are classified as vulnerable to endangered, depending on the species. Conservation efforts include habitat protection, anti-poaching measures, and breeding programs to prevent further population declines.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Anoa", "Native to the dense tropical rainforests, swamps, and mountainous regions of Sulawesi, Indonesia.", 500, "Both species of anoa are endangered due to habitat destruction caused by deforestation for agriculture and logging.", "The anoa is a small, elusive wild buffalo, often referred to as the “dwarf buffalo” due to its compact size. Standing only 70–110 cm tall at the shoulder and weighing between 150 to 300 kg, it is the smallest living wild bovine. Anoas have short, smooth dark brown to black fur, with small, straight horns that curve slightly backward.
Unlike their larger buffalo relatives, anoas are mostly solitary or found in small groups. They are shy and reclusive, avoiding human contact by retreating deep into the forest. Their diet consists of leaves, grasses, ferns, and fruits, and they rely on mud wallows to cool off and protect their skin from parasites.
Despite being legally protected, anoa populations continue to decline due to hunting and habitat fragmentation. Conservation efforts focus on protecting remaining forests, enforcing hunting bans, and breeding programs to ensure their survival. Without urgent action, these unique forest-dwelling buffaloes face an uncertain future.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Javan Eagle", "Endemic to the dense tropical rainforests of Java, Indonesia.", 300, "The Javan eagle is endangered due to habitat destruction from deforestation, illegal logging, and land conversion for agriculture and urban development.", "The Javan eagle is a medium-sized raptor, reaching about 60 cm in length with a wingspan of up to 1.3 meters. It has striking brown plumage with a lighter underside, bold black-and-white wing markings, and a prominent crest of long feathers on its head. This gives it a majestic, almost mythical appearance.
As a top predator, it primarily hunts birds, reptiles, and small mammals, using its sharp talons and powerful beak to capture prey. It soars high above the forest canopy, scanning for movement before diving swiftly to attack.
Javan eagles are monogamous and build large nests in tall trees, where they lay a single egg per breeding cycle. This slow reproduction rate makes population recovery difficult. Conservation efforts focus on protecting their remaining forest habitats, enforcing anti-poaching laws, and rehabilitating rescued individuals to ensure the survival of Java’s rare and iconic raptor.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Tarsius", "The dense tropical rainforests of Southeast Asia, particularly on islands like Sulawesi, Borneo, and Sumatra.", 200, "Tarsiers are endangered due to habitat destruction caused by deforestation, agricultural expansion, and human settlements.", "Tarsiers are among the smallest primates, measuring only 10–15 cm in body length, with an exceptionally long tail that adds another 20–25 cm. They have soft, brownish-gray fur, large bat-like ears, and distinctive, oversized eyes—each eye is larger than its brain, allowing them to see in near-total darkness.
These primates are exceptional jumpers, using their elongated hind limbs to leap distances up to 5 meters between trees. Unlike most primates, they are entirely carnivorous, feeding on insects, small birds, and lizards, which they hunt with their keen vision and sharp claws.
Tarsiers are solitary or live in small family groups, communicating through high-pitched calls. Due to their sensitivity to stress, they struggle in captivity, often refusing to eat or dying prematurely. Conservation efforts focus on protecting their forest habitats and preventing the illegal pet trade to ensure the survival of these unique, nocturnal primates.");

INSERT INTO Animal (Name, Environment, HowManyLeft, ReasonForDanger, Description)
VALUES ("Celebes Crested Macaque", "Native to the tropical rainforests of Sulawesi, Indonesia, primarily inhabiting the northern and central regions of the island.", 200, "The Celebes crested macaque is critically endangered due to habitat destruction from logging, agriculture, and the encroachment of human settlements.", "The Celebes crested macaque is a medium-sized primate known for its striking appearance, with a prominent black crest of hair on its head that gives it a unique, almost “quiffed” look. Its face is mostly bare, with bright pink skin around the eyes and muzzle, while its fur is dense and black, covering the body and limbs. Adult males can weigh up to 12 kg, while females are slightly smaller.
These monkeys are highly social, living in troops of 10 to 30 individuals, with complex social structures and strong bonds between group members. Their diet includes fruits, leaves, seeds, and insects, and they are also known to forage for crops in agricultural areas, which leads to conflicts with local farmers.
The Celebes crested macaque is diurnal and spends most of its time in the trees, where they are adept climbers. Conservation efforts are focused on protecting their rainforest habitats, reducing poaching, and improving human-wildlife relationships to help stabilize their declining populations.");

INSERT INTO School_Post (ID, Owner, Title, Image, Content, Date, Time)  
VALUES (1, 'CovSchool', 'BREAKING: Sumatran Tigers Spotted Forming ''Super Pack'' in Indonesian Jungle!',  
NULL, 'In a shocking turn of events, wildlife researchers in Sumatra have reported an unprecedented phenomenon—Sumatran tigers (Panthera tigris sumatrae) have allegedly begun hunting in packs for the first time in recorded history. Traditionally known as solitary predators, these tigers have been seen working together in groups of four to six individuals, coordinating attacks on large prey such as wild buffalo and even rhinoceroses.  
Dr. Aria Santoso, a field biologist, claims that this behavior may be a response to habitat destruction, forcing the tigers to evolve new hunting strategies. ‘‘We believe this is nature’s way of adapting to the crisis. The Sumatran tiger is proving to be far more intelligent and cooperative than we ever imagined,’’ he stated.  
Local villagers have also reported eerie nighttime roars echoing in unison, suggesting possible communication between groups. Some even fear that these super packs may pose a new threat to human settlements.  
While scientists are scrambling to confirm these reports, experts warn that if this behavior continues, the Sumatran tiger could become the most formidable predator in Southeast Asia. Could this be a new evolutionary leap, or is something even more mysterious at play? Stay tuned!',  
'2025-02-18', '15:00:00'); 

